module.exports = class Data1745714414478 {
    name = 'Data1745714414478'

    async up(db) {
        await db.query(`CREATE TABLE "block" ("id" character varying NOT NULL, "number" integer NOT NULL, "parent_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, CONSTRAINT "PK_d0925763efb591c2e2ffb267572" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "internal_transaction" ("id" character varying NOT NULL, "caller_address" character varying NOT NULL, "transfer_to_address" character varying NOT NULL, "amount" numeric NOT NULL, "rejected" boolean NOT NULL, CONSTRAINT "PK_a260e6e5fee2f818eb8808f9964" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "account_create_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, CONSTRAINT "PK_dd1efd6e44380645dbe27920445" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "transfer_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "from" character varying NOT NULL, "to" character varying NOT NULL, "amount" numeric NOT NULL, CONSTRAINT "PK_3df397a18d47bd34e6338088717" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "transfer_asset_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "asset_name" character varying NOT NULL, "from" character varying NOT NULL, "to" character varying NOT NULL, "amount" numeric NOT NULL, CONSTRAINT "PK_039fc4b2f3bc4028cc44d76cfdb" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "vote_asset_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "votes" text NOT NULL, CONSTRAINT "PK_c4bf3923c7bde8f27f677e8c005" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "vote_witness_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "votes" text NOT NULL, CONSTRAINT "PK_638163d53123f00c7b3237f0474" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "witness_create_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "url" character varying NOT NULL, CONSTRAINT "PK_78122c39f0e46ff0453921295d4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "asset_issue_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "name" character varying NOT NULL, "total_supply" numeric NOT NULL, CONSTRAINT "PK_6a57ce7253b7bb06733dae6bb20" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "witness_update_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "update_url" character varying NOT NULL, CONSTRAINT "PK_eefda2e0df1f7c2c6011752c526" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "participate_asset_issue_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "asset_name" character varying NOT NULL, "amount" numeric NOT NULL, CONSTRAINT "PK_f764f8cce0b147b7eb7516cf152" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "account_update_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "account_name" character varying NOT NULL, CONSTRAINT "PK_bb148812fc64a5854c40bafdca5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "freeze_balance_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "frozen_balance" numeric NOT NULL, "frozen_duration" integer NOT NULL, "resource" character varying NOT NULL, CONSTRAINT "PK_fbc0e6851ad0a5027c03e78ae45" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "unfreeze_balance_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "resource" character varying NOT NULL, CONSTRAINT "PK_b571ecd4ed05b1ecf3cb98d0372" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "withdraw_balance_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, CONSTRAINT "PK_5f534679b173d265f107b303d7b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "unfreeze_asset_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, CONSTRAINT "PK_799a5c8cfaf4f178a49a3980a4c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "update_asset_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "asset_name" character varying NOT NULL, CONSTRAINT "PK_a8952e2873a95eec36a62fa9f47" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "proposal_create_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "parameters" text NOT NULL, CONSTRAINT "PK_50b99a0a968a03571589a4d92ac" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "proposal_approve_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "proposal_id" integer NOT NULL, CONSTRAINT "PK_faec479eca69c829171f1f113b7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "proposal_delete_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "proposal_id" integer NOT NULL, CONSTRAINT "PK_d77023c503f2783a464874ed064" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "set_account_id_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "account_id" character varying NOT NULL, CONSTRAINT "PK_8879256048ab332f8a8bb6ad493" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "custom_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "data" character varying NOT NULL, CONSTRAINT "PK_c04588d23586544e27d8ab9442a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "create_smart_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "contract_name" character varying NOT NULL, "origin_address" character varying NOT NULL, "abi" character varying NOT NULL, "bytecode" character varying NOT NULL, "origin_energy_limit" integer NOT NULL, CONSTRAINT "PK_a4f88cb3cdfb8f9b7ac431598d3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "trigger_smart_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "contract_address" character varying NOT NULL, "data" character varying NOT NULL, "call_value" numeric, CONSTRAINT "PK_19b4cef06a95c9f41efc57127ef" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "get_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "contract_address" character varying NOT NULL, CONSTRAINT "PK_a38fd140290c945ab2e5c847f4e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "update_setting_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "contract_address" character varying NOT NULL, "settings" text NOT NULL, CONSTRAINT "PK_0690fddde8ffaf9b27498af3cab" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "exchange_create_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "first_token_id" character varying NOT NULL, "first_token_balance" numeric NOT NULL, "second_token_id" character varying NOT NULL, "second_token_balance" numeric NOT NULL, CONSTRAINT "PK_8246da0fe3a22cd127f1df5fbba" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "exchange_inject_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "exchange_id" integer NOT NULL, "token_id" character varying NOT NULL, "quant" numeric NOT NULL, CONSTRAINT "PK_a6cc859f78a22fc7e4235623f63" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "exchange_withdraw_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "exchange_id" integer NOT NULL, "token_id" character varying NOT NULL, "quant" numeric NOT NULL, CONSTRAINT "PK_a5b17d82f98b0e936df94b9cdd2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "exchange_transaction_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "exchange_id" integer NOT NULL, "token_id" character varying NOT NULL, "quant" numeric NOT NULL, "expected" numeric NOT NULL, CONSTRAINT "PK_d7cf29ea192780fd3909c40b53c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "update_energy_limit_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "contract_address" character varying NOT NULL, "origin_energy_limit" numeric NOT NULL, CONSTRAINT "PK_9bf623fa9e21259943ada002614" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "account_permission_update_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "owner" text NOT NULL, "witness" text NOT NULL, "actives" text NOT NULL, CONSTRAINT "PK_4487092e69981f17530ad29b027" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "clear_abi_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "contract_address" character varying NOT NULL, CONSTRAINT "PK_3e1d438f980f1b1f401c490934b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "update_brokerage_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "brokerage" integer NOT NULL, CONSTRAINT "PK_fcc0319cb29ebde1f203362a9c8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "shielded_transfer_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "transparent_from_address" character varying NOT NULL, "transparent_to_address" character varying NOT NULL, "amount" numeric NOT NULL, "shielded_transaction_data" character varying NOT NULL, CONSTRAINT "PK_e2fdf1a71b4db421d03b8e1b11c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "market_sell_asset_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "asset_name" character varying NOT NULL, "amount" numeric NOT NULL, CONSTRAINT "PK_5f4147eb011accc51b9fb128442" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "market_cancel_order_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "order_id" character varying NOT NULL, CONSTRAINT "PK_988b7624f0899c97a6325c72fc3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "freeze_balance_v2_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "frozen_balance" numeric NOT NULL, "resource" character varying NOT NULL, CONSTRAINT "PK_efcba54a1a56f578f93592b2a50" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "unfreeze_balance_v2_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, CONSTRAINT "PK_81f6bacee8b007551b799e48f8d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "withdraw_expire_unfreeze_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, CONSTRAINT "PK_21293cbbdfcf5d05fb2571e5fbd" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "delegate_resource_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "receiver_address" character varying NOT NULL, "balance" numeric NOT NULL, "resource" character varying NOT NULL, "lock" boolean NOT NULL, CONSTRAINT "PK_5d0a89cab6f07153fa308df1d55" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "un_delegate_resource_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, "receiver_address" character varying NOT NULL, "balance" numeric NOT NULL, "resource" character varying NOT NULL, CONSTRAINT "PK_c6a522e9273ea57af4f2efeaa2a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "cancel_all_unfreeze_v2_contract_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "owner_address" character varying NOT NULL, CONSTRAINT "PK_a73e2319089f502113246cc5480" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "generic_transaction" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "type" character varying NOT NULL, "contract_address" character varying NOT NULL, "fee" character varying NOT NULL, "result" character varying NOT NULL, CONSTRAINT "PK_cc38341cd401615c2837ac6a440" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "destroyed_black_funds_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "black_listed_user" character varying NOT NULL, "balance" numeric NOT NULL, CONSTRAINT "PK_9ee4dc7cdea369625f94ebb26ae" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "issue_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "amount" numeric NOT NULL, CONSTRAINT "PK_38fe0ddaada1e87585adb5cfa8a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "redeem_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "amount" numeric NOT NULL, CONSTRAINT "PK_bcb3a0fd3649dd7d6b74348b7f3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "deprecate_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "new_address" character varying NOT NULL, CONSTRAINT "PK_af9f0ce92c52af6c2b33a694604" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "added_black_list_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "user" character varying NOT NULL, CONSTRAINT "PK_873ebb63e9eacfd492d73376772" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "removed_black_list_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "user" character varying NOT NULL, CONSTRAINT "PK_3b1ca23b7c9ee382d80b09ebdca" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "params_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "fee_basis_points" numeric NOT NULL, "max_fee" numeric NOT NULL, CONSTRAINT "PK_c93d0c01236b13a9209ff21a47d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "pause_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, CONSTRAINT "PK_9def8f2298caec7ba9746c265c4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "unpause_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, CONSTRAINT "PK_5655c9563a30e9574dead82e03c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "ownership_transferred_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "previous_owner" character varying NOT NULL, "new_owner" character varying NOT NULL, CONSTRAINT "PK_b6ace52b7a8eca00208677b4933" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "approval_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "owner" character varying NOT NULL, "spender" character varying NOT NULL, "value" numeric NOT NULL, CONSTRAINT "PK_4a04c4c5639ee9d282c55fac735" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "transfer_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "from" character varying NOT NULL, "to" character varying NOT NULL, "value" numeric NOT NULL, CONSTRAINT "PK_2a4e1dce9f72514cd28f554ee2d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "generic_log_event" ("id" character varying NOT NULL, "block_hash" character varying NOT NULL, "transaction_hash" character varying NOT NULL, "contract_address" character varying NOT NULL, "topics" text NOT NULL, "data" character varying NOT NULL, CONSTRAINT "PK_14e5dee0cd181c401cbe93a594f" PRIMARY KEY ("id"))`)
    }

    async down(db) {
        await db.query(`DROP TABLE "block"`)
        await db.query(`DROP TABLE "internal_transaction"`)
        await db.query(`DROP TABLE "account_create_contract_transaction"`)
        await db.query(`DROP TABLE "transfer_contract_transaction"`)
        await db.query(`DROP TABLE "transfer_asset_contract_transaction"`)
        await db.query(`DROP TABLE "vote_asset_contract_transaction"`)
        await db.query(`DROP TABLE "vote_witness_contract_transaction"`)
        await db.query(`DROP TABLE "witness_create_contract_transaction"`)
        await db.query(`DROP TABLE "asset_issue_contract_transaction"`)
        await db.query(`DROP TABLE "witness_update_contract_transaction"`)
        await db.query(`DROP TABLE "participate_asset_issue_contract_transaction"`)
        await db.query(`DROP TABLE "account_update_contract_transaction"`)
        await db.query(`DROP TABLE "freeze_balance_contract_transaction"`)
        await db.query(`DROP TABLE "unfreeze_balance_contract_transaction"`)
        await db.query(`DROP TABLE "withdraw_balance_contract_transaction"`)
        await db.query(`DROP TABLE "unfreeze_asset_contract_transaction"`)
        await db.query(`DROP TABLE "update_asset_contract_transaction"`)
        await db.query(`DROP TABLE "proposal_create_contract_transaction"`)
        await db.query(`DROP TABLE "proposal_approve_contract_transaction"`)
        await db.query(`DROP TABLE "proposal_delete_contract_transaction"`)
        await db.query(`DROP TABLE "set_account_id_contract_transaction"`)
        await db.query(`DROP TABLE "custom_contract_transaction"`)
        await db.query(`DROP TABLE "create_smart_contract_transaction"`)
        await db.query(`DROP TABLE "trigger_smart_contract_transaction"`)
        await db.query(`DROP TABLE "get_contract_transaction"`)
        await db.query(`DROP TABLE "update_setting_contract_transaction"`)
        await db.query(`DROP TABLE "exchange_create_contract_transaction"`)
        await db.query(`DROP TABLE "exchange_inject_contract_transaction"`)
        await db.query(`DROP TABLE "exchange_withdraw_contract_transaction"`)
        await db.query(`DROP TABLE "exchange_transaction_contract_transaction"`)
        await db.query(`DROP TABLE "update_energy_limit_contract_transaction"`)
        await db.query(`DROP TABLE "account_permission_update_contract_transaction"`)
        await db.query(`DROP TABLE "clear_abi_contract_transaction"`)
        await db.query(`DROP TABLE "update_brokerage_contract_transaction"`)
        await db.query(`DROP TABLE "shielded_transfer_contract_transaction"`)
        await db.query(`DROP TABLE "market_sell_asset_contract_transaction"`)
        await db.query(`DROP TABLE "market_cancel_order_contract_transaction"`)
        await db.query(`DROP TABLE "freeze_balance_v2_contract_transaction"`)
        await db.query(`DROP TABLE "unfreeze_balance_v2_contract_transaction"`)
        await db.query(`DROP TABLE "withdraw_expire_unfreeze_contract_transaction"`)
        await db.query(`DROP TABLE "delegate_resource_contract_transaction"`)
        await db.query(`DROP TABLE "un_delegate_resource_contract_transaction"`)
        await db.query(`DROP TABLE "cancel_all_unfreeze_v2_contract_transaction"`)
        await db.query(`DROP TABLE "generic_transaction"`)
        await db.query(`DROP TABLE "destroyed_black_funds_event"`)
        await db.query(`DROP TABLE "issue_event"`)
        await db.query(`DROP TABLE "redeem_event"`)
        await db.query(`DROP TABLE "deprecate_event"`)
        await db.query(`DROP TABLE "added_black_list_event"`)
        await db.query(`DROP TABLE "removed_black_list_event"`)
        await db.query(`DROP TABLE "params_event"`)
        await db.query(`DROP TABLE "pause_event"`)
        await db.query(`DROP TABLE "unpause_event"`)
        await db.query(`DROP TABLE "ownership_transferred_event"`)
        await db.query(`DROP TABLE "approval_event"`)
        await db.query(`DROP TABLE "transfer_event"`)
        await db.query(`DROP TABLE "generic_log_event"`)
    }
}
